framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            email_sender:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            # uncomment tu use sending email via messenger
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: email_sender
